// This file is auto-generated by @hey-api/openapi-ts

/**
 * Generic request for any agent that takes a simple prompt.
 */
export type AgentRequest = {
  prompt: string;
  context?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Generic response for an agent that returns a simple text response.
 */
export type AgentResponse = {
  response: string;
  agent_id: string;
  execution_time: number;
  metadata?: {
    [key: string]: unknown;
  } | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * The final, structured response from our endpoint.
 */
export type NewCardAgentResponse = {
  card_data: NewCardData;
  agent_id: string;
  execution_time: number;
  metadata: {
    [key: string]: unknown;
  };
};

/**
 * The structured data for our Kanban card. This is our target output.
 */
export type NewCardData = {
  title: string;
  description: string;
  task_type: TaskType;
  status?: "todo";
  parameters: ResearchParameters;
};

export type OutboundCallRequest = {
  /**
   * Numéro de téléphone du destinataire (format E.164)
   */
  target_number: string;
  /**
   * Texte de la Market Overview à résumer
   */
  market_overview: string;
  /**
   * Nom de la personne à qui on passe l'appel
   */
  name: string;
  /**
   * Action à entreprendre pendant l'appel
   */
  action_to_take: string;
};

export type OutboundCallResponse = {
  success: boolean;
  call_id?: string | null;
  message: string;
  assistant_id?: string | null;
  execution_time: number;
  metadata?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Parameters for a research task. Pydantic validates this for us.
 */
export type ResearchParameters = {
  topics: Array<string>;
  scope: string;
};

/**
 * The types of tasks our agent can create. Start with one, add more later.
 */
export type TaskType = "research_task";

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type TriggerAgentData = {
  body: AgentRequest;
};

export type TriggerAgentResponse = AgentResponse;

export type TriggerAgentError = HTTPValidationError;

export type TriggerOutboundCallData = {
  body: OutboundCallRequest;
};

export type TriggerOutboundCallResponse = OutboundCallResponse;

export type TriggerOutboundCallError = HTTPValidationError;

export type CreateNewCardFromPromptData = {
  body: AgentRequest;
};

export type CreateNewCardFromPromptResponse = NewCardAgentResponse;

export type CreateNewCardFromPromptError = HTTPValidationError;

export type PerformDeepSearchData = {
  body: AgentRequest;
};

export type PerformDeepSearchResponse = AgentResponse;

export type PerformDeepSearchError = HTTPValidationError;
